=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/schema/inventory/device-post.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id":"device-put.json",
  "properties": {
    "provider": {
      "$ref": "#/definitions/provider"
    },
    "type": {
      "type": "string"
    },
    "macAddress": {
      "type": "string"
    },
    "comment": {
      "type": "string"
    },
    "location": {"$ref":"#/definitions/location"},
    "product": {"$ref":"#/definitions/product"},
    "deviceState": {"$ref":"#/definitions/deviceState"}
  },
  "required": [
    "provider",
    "type",
    "macAddress",
    "comment",
    "location",
    "product",
    "deviceState"
  ],
  "definitions": {
    "provider": {
      "properties": {
        "href": {
          "type": "string"
        },
        "name": {
          "enum": ["MERCURY"]
        },
        "id": {
          "type": "integer"
        }
      },
      "required": [
        "href",
        "name",
        "id"
      ]
    },
    "location":{
      "properties": {
        "aggrZone": {
          "type": "string"
        },
        "datacenterId":{
          "type":"integer"
        },
        "datacenter": {
          "type": "string"
        },
        "cabinetName": {
          "type": "string"
        },
        "cabinetStartingSpace": {
          "type": "integer"
        }
      }
    },
    "product":{
      "properties": {
        "productCatalogDetails": {
          "properties": {
            "href": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "offeringDescription": {
              "type": "string"
            }
          }
        },
        "offerServiceDetails": {
          "properties": {
            "href": {
              "type": "string"
            },
            "productId": {
              "type": "string"
            },
            "productName": {
              "type": "string"
            }
          }
        }
      }
    },
    "deviceState":{
      "properties": {
        "state": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    }
  }
}

=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/examples/inventory/device-post.json
{
  "provider":{
    "href": "mercury/device/123123123",
    "name":"MERCURY",
    "id": 123123123
  },
  "type": "SERVER",
  "macAddress": "d4-ae-52-86-d8-95",
  "comment": "Comment from latest modification",
  "location": {
    "aggrZone": "IAD3:Public:Zone403-11",
    "datacenter": "IAD3",
    "datacenterId":12,
    "cabinetName":"MX11",
    "cabinetStartingSpace": 20
  },
  "product": {
    "productCatalogDetails": {
      "href": "productCatalogLink",
      "id": 123,
      "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
    },
    "offerServiceDetails": {
      "href": "offerlink",
      "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
      "productName": "48GB Dual Processor Hex Core Dedicated Server"
    }
  },
  "deviceState": {
    "state": "PRODUCTION",
    "comment": "Prod comment"
  }
}

=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/examples/inventory/devices-post.json
[{
  "provider":{
    "href": "mercury/device/123123123",
    "name":"MERCURY",
    "id": 123123123
  },
  "type": "SERVER",
  "macAddress": "d4-ae-52-86-d8-95",
  "comment": "Adding new server to inventory",
  "location": {
    "aggrZone": "IAD3:Public:Zone403-11",
    "datacenterId":12,
    "datacenter": "IAD3",
    "cabinetName":"MX11",
    "cabinetStartingSpace": 20
  },
  "product": {
    "productCatalogDetails": {
      "href": "productCatalogLink",
      "id": 123,
      "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
    },
    "offerServiceDetails": {
      "href": "offerlink",
      "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
      "productName": "48GB Dual Processor Hex Core Dedicated Server"
    }
  },
  "deviceState": {
    "state": "PRODUCTION",
    "comment": "Prod comment"
  }
}]
