=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/schema/inventory/device-get.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "provider":{
      "properties":{
        "href":{"type":"string"},
        "name":{"enum":["MERCURY"]},
        "id":{"type":"integer"}
      }
    },
    "type": {
      "enum": [
        "SERVER",
        "FIREWALL"
      ]
    },
    "macAddress": {
      "type": "string"
    },
    "comment": {
      "type": "string"
    },
    "deleted": {
      "type": "boolean"
    },
    "location": {
      "$ref": "#/definitions/location"
    },
    "product": { "$ref": "#/definitions/product" },
    "inventoryState": {
      "type": "object",
      "oneOf": [{
        "$ref": "#/definitions/inventoryStateNew"
      },{
        "$ref": "#/definitions/inventoryStateGeneral"
      }, {
        "$ref": "#/definitions/inventoryStateAllocated"
      }]
    },
    "deviceState": {
      "type": "object",
      "properties": {
        "state": {
          "enum": ["TEST", "PRE-PRODUCTION", "PRODUCTION"]
        },
        "timestamp": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "lastModified": {
      "$ref": "#/definitions/modification"
    },
    "created": {
      "$ref": "#/definitions/modification"
    }
  },
  "required": [
    "id",
    "type",
    "macAddress",
    "comment",
    "deleted",
    "location",
    "product",
    "inventoryState",
    "deviceState"
  ],
  "definitions": {
    "modification": {
      "properties": {
        "userId": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        }
      }
    },
    "automationEvent": {
      "properties": {
        "href": {
          "type": "string"
        },
        "eventId": {
          "type": "string"
        }
      }
    },
    "location": {
      "properties": {
        "href": {
          "type": "string"
        },
        "aggrZone": {
          "type": "string"
        },
        "datacenterId":{
          "type":"integer"
        },
        "datacenter": {
          "type": "string"
        },
        "cabinetName":{
          "type":"string"
        },
        "cabinetStartingSpace": {
          "type": "integer"
        }
      }
    },
    "product": {
      "properties": {
        "productCatalog": {
          "properties": {
            "href": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "offeringDescription": {
              "type": "string"
            }
          }
        },
        "offerService": {
          "properties": {
            "href": {
              "type": "string"
            },
            "productId": {
              "type": "string"
            },
            "productName": {
              "type": "string"
            }
          }
        }
      }
    },
    "quote": {
      "properties": {
        "href": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "salesPersonUserId": {
          "type": "string"
        },
        "opportunity": {
          "type": "string"
        }
      }
    },
    "device": {
      "properties": {
        "deviceService": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          }
        },
        "core": {
          "properties": {
            "href": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          }
        }
      }
    },
    "account": {
      "properties": {
        "core": {
          "properties": {
            "href": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          }
        }
      }
    },
    "inventoryStateNew": {
      "properties": {
        "state": {
          "enum": ["NEW"]
        },
        "provider": {
          "properties": {
            "href": {
              "type": "string"
            },
            "name": {
              "enum": ["MERCURY"]
            },
            "id": {
              "type": "integer"
            }
          },
          "required": [
            "href",
            "name",
            "id"
          ]
        },
        "userId": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        }
      },
      "required": [
        "state",
        "userId",
        "comment"
      ]
    },
    "inventoryStateGeneral": {
      "properties": {
        "state": {
          "enum": ["AVAILABLE", "MAINTENANCE", "SUSPENDED", "DECOMMISSIONED", "DELETED"]
        },
        "userId": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "automationEvent": {
          "$ref": "#/definitions/automationEvent"
        }
      },
      "required": [
        "state",
        "userId",
        "comment",
        "automationEvent"
      ]
    },
    "inventoryStateAllocated": {
      "properties": {
        "state": {
          "enum": ["ALLOCATED"]
        },
        "userId": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "device": {
          "$ref": "#/definitions/device"
        },
        "account": {
          "$ref": "#/definitions/account"
        },
        "quote": {
          "$ref": "#/definitions/quote"
        },
        "automationEvent": {
          "$ref": "#/definitions/automationEvent"
        }
      },
      "required": [
        "state",
        "userId",
        "comment",
        "device",
        "account"
      ]
    }
  }
}

=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/examples/inventory/device-get.json
{
  "id": "530ab29ebcae151ade6f9b2f",
  "provider":{
    "href": "mercury/device/123123123",
    "name":"MERCURY",
    "id": 123123123
  },
  "type": "SERVER",
  "macAddress": "d4-ae-52-86-d8-95",
  "comment": "Comment from latest modification",
  "deleted": false,
  "location": {
    "aggrZone": "IAD3:Public:Zone403-11",
    "datacenterId":12,
    "datacenter": "IAD3",
    "cabinetName":"MX11",
    "cabinetStartingSpace": 20
  },
  "product": {
    "productCatalogDetails": {
      "href": "productCatalogLink",
      "id": 123,
      "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
    },
    "offerServiceDetails": {
      "href": "offerlink",
      "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
      "productName": "48GB Dual Processor Hex Core Dedicated Server"
    }
  },
  "inventoryState": {
    "state": "ALLOCATED",
    "userId": "automation",
    "comment": "TEST",
    "timestamp": "1/1/1111T11:11:11Z",
    "device": {
      "deviceService": {
        "href": "deviceServiceLink",
        "id": "12312312312"
      },
      "core": {
        "href": "core.rackspace.com/device/12312312312",
        "id": "12312312312"
      }
    },
    "account": {
      "href": "core/account/612345",
      "accountId": 612345
    },
    "quote": {
      "href": ".../quotes/9898989",
      "id": "9898989",
      "salesPersonUserId": "jim1234",
      "opportunity": "9898989898"
    },
    "automationEvent": {
      "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
      "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
    }
  },
  "deviceState": {
    "type": "PRODUCTION",
    "comment": "Prod comment",
    "timestamp": "1/1/1111T11:11:11Z"
  },
  "lastModified": {
    "userId": "bob",
    "timestamp": "1/1/1111T11:11:11Z"
  },
  "created": {
    "userId": "bob",
    "timestamp": "1/1/1111T11:11:11Z"
  }
}

=== gopal2109/Data/GO/rapid-provisioning-inventory-api/docs/examples/inventory/device-list-get.json
[
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "ALLOCATED",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "device": {
        "deviceService": {
          "href": "deviceServiceLink",
          "id": "12312312312"
        },
        "core": {
          "href": "core.rackspace.com/device/12312312312",
          "id": "12312312312"
        }
      },
      "account": {
        "links": {
          "account": "accountlink",
          "device": "devicelink"
        },
        "accountId": 612345,
        "deviceId": 572341
      },
      "quote": {
        "href": ".../quotes/9898989",
        "id": "9898989",
        "salesPersonUserId": "jim1234",
        "opportunity": "9898989898"
      },
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  },
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "AVAILABLE",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  },
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "MAINTENANCE",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  },
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "SUSPENDED",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  },
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "DECOMMISSIONED",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  },
  {
    "id": "530ab29ebcae151ade6f9b2f",
    "type": "SERVER",
    "macAddress": "d4-ae-52-86-d8-95",
    "comment": "Comment from latest modification",
    "deleted": false,
    "location": {
      "aggrZone": "IAD3:Public:Zone403-11",
      "datacenterId":12,
      "datacenter": "IAD3",
      "cabinet":"MX11",
      "cabinetStartingSpace": 20
    },
    "product": {
      "productCatalogDetails": {
        "href": "productCatalogLink",
        "id": 123,
        "offeringDescription": "48GB Dual Processor Hex Core Dedicated Server"
      },
      "offerServiceDetails": {
        "href": "offerlink",
        "productId": "902e1779-1356-4a95-85fa-b50001ef874c",
        "productName": "48GB Dual Processor Hex Core Dedicated Server"
      }
    },
    "inventoryState": {
      "state": "DELETED",
      "userId": "automation",
      "comment": "TEST",
      "timestamp": "1/1/1111T11:11:11Z",
      "automationEvent": {
        "href": ".../events/45bd38cb-f401-4873-a7a5-d5afa2fcc0cd",
        "eventId": "45bd38cb-f401-4873-a7a5-d5afa2fcc0cd"
      }
    },
    "deviceState": {
      "state": "PRODUCTION",
      "comment": "Prod comment",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "lastModified": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    },
    "created": {
      "userId": "bob",
      "timestamp": "1/1/1111T11:11:11Z"
    }
  }
]
